spring.application.name=setlistify
# ===================================================================
# Spotify OAuth2 Infrastructure Configuration
# ===================================================================
spotify.client-id=${SPOTIFY_CLIENT_ID}
# Note: We are using 127.0.0.1 loopback IP to satisfy with Spotify's security rules
spotify.redirect-uri=http://127.0.0.1:8080/api/v1/auth/callback
spotify.scopes=playlist-modify-public playlist-modify-private user-read-private user-read-email